### PR TITLE
Clipboard fixes on Linux (X11)

### PR DESCRIPTION
**Pull request by Tortue95**
To resolve the issue of local clipboard corruption on Linux when non-text items are copied #81 , I suggest using "Xfixes" and the "XFixesSelectSelectionInput" function. This will allow us to retrieve events on clipboard modifications that are now available in most X11 engines today. However, for compatibility reasons, I will keep a retrocompatibility option in case Xfixes version 1.0 is not available.

This solution will help solve the problem of losing data and make it easier for users to transfer data between different applications. I have tested this solution on multiple X11 systems and it works as expected.

Please let me know if there are any concerns or questions regarding this proposal. Thank you!

### CODE REVIEW

**Comment by chrisd1100** [comment]
Thanks for this R&D work!

So to summarize, because this clipboard handling is confusing and I honestly forget exactly how it works -- By default, we needed to poll for CLIPBOARD selection ownership changes and if a change was detected we convert the new selection to UTF8 with `XConvertSelection`. Xfixes is able to detect when this happens without polling.

Then, in `SelectionNotify` we always force the owner back to the libmatoya window so we receive future `SelectionNotify` events. With Xfixes, this does not seem to be necessary.

Does Xfixes somehow send `SelectionNotify` to all windows regardless of whether they are the owner? Also, since we are still calling `XConvertSelection` with UTF8, why doesn't the corruption occur?

**Comment by Tortue95** [comment]
From what I understand, as I have never worked with X11 before.
the problem comes from the "app_handle_selection_request()" function, which, with the "XChangeProperty()" function inside, resets the clipboard to the last values that can be converted to UTF8.
With XFixe, to detect clipboard changes, it is not necessary for libmaoya to be the permanent owner of the clipboard. It is therefore no longer necessary to call "XSetSelectionOwner()" and thus "app_handle_selection_request()".
It would probably have been possible to do an "XChangeProperty()" on all possible atom types. But not being the permanent owner of the clipboard and not rewriting the clipboard with the same thing every time, seems cleaner to me, as it avoids concurrency issues that could occur with other applications doing the same thing, like two applications using libmatoya, for example.

After reviewing the code, it is true that it is not necessary to have events on SelectionRequest when XFixe is available. This code should also have an IF statement:

```
case SelectionNotify:
	app_handle_selection_notify(ctx, &event->xselection);
	break;
```

**Comment by Tortue95** [comment]
Excuse me, I was mistaken because without the events on SelectionNotify and the function "app_handle_selection_notify()," we can no longer use "MTY_AppSetClipboard()... we need to keep it.

**Comment by Tortue95** [comment]
Great :) thank you for taking the time to review it, and for integrating it into the master branch.

**Pull request merged**
